name: Keep Render Awake
on:
  schedule:
    - cron: "*/10 * * * *" # This triggers every 10 minutes
  workflow_dispatch: # This allows you to run it manually to test

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render URL
        run: curl -s https://copypaste-app.onrender.com > /dev/null
